version: '3'
services:
  php7:
    container_name: laravue_php7
    ports:
      - "8080:80"
    build:
        context: "./docker/php"
        dockerfile: "Dockerfile"
    volumes:
        - .:/var/www/html
    networks:
      - laravel_vue

  node:
    container_name: laravel_node
    build:
      context: "./docker/node"
      dockerfile: Dockerfile
    volumes:
        - .:/var/www/html
    tty: true
    ports:
        - "3000:3000"

  db:
    container_name: laravue_db
    ports:
     - "3306:3306"
    build:
        context: "./docker/mysql"
        dockerfile: "Dockerfile"        
    environment:
      MYSQL_DATABASE: laravue
      MYSQL_USER: laravue_user
      MYSQL_PASSWORD: laravue_password
      MYSQL_ROOT_PASSWORD: laravue_password
    networks:
      - laravel_vue

networks:
  laravel_vue:
    driver: "bridge"      